apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-serving.name" . }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
data:
  MLFLOW_TRACKING_URI: {{ .Values.env.mlflowTrackingUri | quote }}
  MODEL_URI: {{ .Values.env.modelUri | quote }}
